# Generated by Django 4.2.8 on 2024-03-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='voucher',
            field=models.ManyToManyField(blank=True, to='core.voucher'),
        ),
        migrations.AddField(
            model_name='product',
            name='voucher',
            field=models.ManyToManyField(blank=True, to='core.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
