# Generated by Django 4.2.8 on 2024-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cartorderproducts_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='name',
            field=models.CharField(default='non', max_length=200),
            preserve_default=False,
        ),
    ]
