# Generated by Django 4.2.8 on 2024-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
