# Generated by Django 4.2.8 on 2024-02-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cartorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
    ]
