# Generated by Django 5.0 on 2023-12-24 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Brands',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='brand',
        ),
    ]
