# Generated by Django 4.2.8 on 2023-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_patrick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
                ('title', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Patrick',
        ),
    ]
