name: Deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip  # Install Python and pip
          pip3 install -r requirements.txt  # Install project dependencies
      
      - name: Run database migrations
        run: python manage.py makemigrations

      - name: Run database migrat
        run: python manage.py migrate

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Restart Django gunicorn server
        run: sudo systemctl restart gunicorn.service  # Restart Gunicorn or uWSGI or whatever you're using

      - name: Restart Django nginx server
        run: sudo systemctl restart nginx.service
```
